services:

#
#   UNCOMMENT TO RUN LOAD TEST
#
#    k6:
#       image: grafana/k6:1.7.0
#       container_name: k6
#       volumes:
#           - ./scripts/k6:/scripts
#       command: run /scripts/load-script.js

    postgres:
        image: postgres:15.17-alpine
        restart: always
        shm_size: 128mb
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: default_user
            POSTGRES_PASSWORD: example
            POSTGRES_DB: default_db
        volumes:
            - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

    kafka0:
        image: apache/kafka:4.2.0
        hostname: kafka0
        container_name: kafka0
        ports:
            - "9092:9092"
            - "9997:9997"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_JMX_PORT: 9997
            KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:29093'
            KAFKA_LISTENERS: 'PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
            KAFKA_HEAP_OPTS: "-Xms2g -Xmx2g"
        healthcheck:
            test: nc -z localhost 9092 || exit -1
            start_period: 15s
            interval: 5s
            timeout: 10s
            retries: 10

    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
            - "9090:9090"
        depends_on:
            kafka0:
                condition: service_healthy
        environment:
            SERVER_PORT: 9090
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
            KAFKA_CLUSTERS_0_METRICS_PORT: 9997
            DYNAMIC_CONFIG_ENABLED: 'true'

    aggregator-service:
        container_name: mdb-aggregator
        hostname: mdb-aggregator
        image: mzalietin/mdb-aggregator:0.0.1
        ports:
            - "8081:8081" # Movie API
            - "8082:8082" # Movie Review API
            - "8083:8083" # User API
            - "8084:8084" # Query API
        depends_on:
            kafka0:
                condition: service_healthy
            postgres:
                condition: service_started

    gateway-service:
        container_name: mdb-gateway
        hostname: mdb-gateway
        image: mzalietin/mdb-gateway:0.0.1
        ports:
            - "8080:8080"
        depends_on:
            aggregator-service:
                condition: service_started
